site_name: SecurityGames.net

logo: assets/images/logo/security-games-net.jpg

theme:
  name: material
  highlightjs: true
  hljs_languages:
      - yaml
  shortcuts:
      help: 72    # h ###help: 191    # ?
      next: 78     # n
      previous: 80 # p
      search: 83   # s
  navigation_depth: 3     
  



extra_css:
  - assets/css/extra.css

extra_javascript:
  - assets/js/extra.js


# source

locale: en

