site_name: SecurityGames.net

theme:
  name: material
  logo: assets/images/logo/security-games-net.jpg
  highlightjs: true
  hljs_languages:
      - yaml
  shortcuts:
      help: 72     # h ###help: 191    # ?
      next: 78     # n
      previous: 80 # p
      search: 83   # s
  navigation_depth: 4
  language: en
  palette: 

    # Palette toggle for light mode
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: blue
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

#extra_css:
#  - assets/css/extra.css

#extra_javascript:
#  - assets/js/extra.js

# source

locale: en

extra:
  generator: false
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/antoniofeijaouk
    - icon: fontawesome/brands/twitter 
      link: https://twitter.com/AntonioFeijaoUK
    - icon: fontawesome/brands/github
      link: https://github.com/AntonioFeijaoUK
    - icon: fontawesome/brands/instagram
      link: https://instagram.com/AntonioFeijaoUK
      
copyright: Copyright &copy; 2022 <a href="https://www.antoniofeijao.com/">Antonio Feijao UK</a> 

plugins:
  - git-revision-date-localized:
      enable_creation_date: iso_datetime
      type: date
      enable_creation_date: true
      fallback_to_build_date: true





