site_name: SecurityGames.net

logo: /assets/images/logo/security-games-net.jpg

theme:
  name: material
  highlightjs: true
  hljs_languages:
      - yaml
  shortcuts:
      help: 72     # h ###help: 191    # ?
      next: 78     # n
      previous: 80 # p
      search: 83   # s
  navigation_depth: 4
  language: en
  palette: 

    # Palette toggle for light mode
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: deep orange
      accent: red
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    



extra_css:
  - assets/css/extra.css

extra_javascript:
  - assets/js/extra.js


# source

locale: en

