# Theme sourced from https://github.com/pages-themes/hacker

remote_theme: pages-themes/hacker
#remote_theme: pages-themes/hacker@v0.2.0


plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one


title: www.SecurityGames.Net

description: Cyber Security hands-on games and exercises to improve your cyber-security, command line and coding skills.

show_downloads: false

#google_analytics: [Your Google Analytics tracking ID]

author: Antonio Feijao UK

