# Theme sourced from https://github.com/pages-themes/hacker

remote_theme: pages-themes/hacker
#remote_theme: pages-themes/hacker@v0.2.0


plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one


title: www.SecurityGames.Net. Cyber Security hands-on games. Hands-on exercises.

description: A place for cyber-security practice on hands-on games. Practice and gain cyber security skills. Improve your command line and coding skills.

show_downloads: false

#google_analytics: [Your Google Analytics tracking ID]
